<?php

namespace App;

use App\Models\Cart;
use App\Models\Media;
use App\Models\Order;
use App\Models\Product;
use App\Models\ProductReview;
use App\Models\Profile;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
//        static::created(static::createCartClause());
    }

    public const TYPE_LIKE = 1;
    public const TYPE_UNLIKE = -1;

    public const ROLE_ADMIN = 'admin';
    public const ROLE_USER = 'user';
    public const ROLE_MANGER = 'manager';

    public const ROLE_CONTENT_EDITOR = 'content_editor';

    public const USER_ROLE = [
        self::ROLE_ADMIN          => '超级管理员',
        self::ROLE_MANGER         => '管理员',
        self::ROLE_USER           => '普通用户',
        self::ROLE_CONTENT_EDITOR => '内容编辑',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
//    protected $fillable = [
//        'name', 'email', 'password',
//    ];

    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'email_verified_at',
        'created_at',
        'updated_at',
    ];
    protected $appends = [

    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function format(): array
    {
        return [
            'id'         => $this->id,
            'name'       => $this->name,
            'email'      => $this->email,
            'avatar'     => $this->avatar,
            'avatar_url' => $this->avatarUrl,
        ];
    }

    public function setPasswordAttribute($value): void
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public function setResetTokenAttribute($value): void
    {
//        $this->attributes['reset_token'] = Uuid::uuid4()->toString();
    }

    public function avatar(): \Illuminate\Database\Eloquent\Relations\MorphOne
    {
        return $this->morphOne(Media::class, 'mediable');
    }

    public function checkPassword($value): bool
    {
        return Hash::check($value, $this->attributes['password']);
    }

    public function getAvatarUrlAttribute()
    {
        return $this->avatar ? Storage::url($this->avatar->filename) : null;
    }

    public function cart(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(Cart::class);
    }

    public function profile(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(Profile::class);
    }

    public function getIsAdminAttribute(): bool
    {
        return $this->attributes['role'] === self::ROLE_ADMIN;
    }

    public function productReviews(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(ProductReview::class);
    }

    public function orders(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Order::class);
    }

    public function favoriteProducts(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'user_favorite_product')->withTimestamps();
    }
    public function existsFavoriteProduct($product_id): bool
    {
        return $this->favoriteProducts()->wherePivot('product_id', $product_id)->exists();
    }

    public function hasFavoriteProducts(): bool
    {
        return $this->favoriteProductsCount() > 0;
    }


    public function favoriteProductsCount():int
    {
        return $this->favoriteProducts->count();
    }


    public function likeReviews(): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'user_like_review','user_id','review_id')
            ->withPivot('like')->withTimestamps();
    }

    public function likeReviewsCount()
    {
        return $this->likeReviews->count();
    }

    public function existsLikeReviews($product_id): bool
    {
        return $this->likeReviews()->wherePivot('product_id', $product_id)->exists();
    }

    public function hasLikeReviews(): bool
    {
        return $this->likeReviewsCount() > 0;
    }

    public function scopeWithMostBlogPosts(Builder $query)
    {
        return $query->withCount('blogPosts')->orderBy('blog_posts_count', 'desc');
    }

//    public function scopeWithMostBlogPostsLastMonth(Builder $query)
//    {
//        return $query->withCount(['blogPosts' => function (Builder $query) {
//            $query->whereBetween(static::CREATED_AT, [now()->subMonths(1), now()]);
//        }])->has('blogPosts', '>=', 1)
//            ->orderBy('blog_posts_count', 'desc');
//    }
//    public function reviewProducts(){
////        return $this->hasManyThrough()
//    }

    public function scopeWithMostCommentsLastMonth(Builder $query)
    {
        return $query->withCount([
            'reviews' => function (Builder $query) {
                $query->whereBetween(static::CREATED_AT, [now()->subMonths(1), now()]);
            },
        ])->has('reviews', '>=', 1)
            ->orderBy('reviews_count', 'desc');
    }

    public function scopeThatHasCommentedOnProduct(Builder $query, Product $product)
    {
        return $query->whereHas('reviews', function ($query) use ($product) {
            return $query->where('product_id', '=', $product->id);
        });
    }


    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}
